const products = [
	{
		id: 1,
		type: 'phone',
		name: 'Xiaomi Redmi Note 10S 6/128GB Onyx Gray',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 1099.0,
		sale: true,
		saleAmount: 200.0,
		image: './images/phone1.png',
	},
	{
		id: 2,
		type: 'phone',
		name: 'Samsung Galaxy A53 5G 6/128GB 120Hz Black',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 2099.0,
		sale: true,
		saleAmount: 400.0,
		image: './images/phone2.png',
	},
	{
		id: 3,
		type: 'phone',
		name: 'Samsung Galaxy A32 SM-A325F 4/128GB Black',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 1299.0,
		sale: true,
		saleAmount: 300.0,
		image: './images/phone3.png',
	},
	{
		id: 4,
		type: 'phone',
		name: 'Apple iPhone 13 128GB Starlight',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 4499.0,
		sale: false,
		image: './images/phone4.png',
	},
	{
		id: 5,
		type: 'phone',
		name: 'ASUS ZenFone 8 8/128GB Black',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 2999.0,
		sale: true,
		saleAmount: 700.0,
		image: './images/phone5.png',
	},
	{
		id: 6,
		type: 'phone',
		name: 'Apple iPhone 11 64GB Black',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 2599.0,
		sale: false,
		image: './images/phone6.png',
	},
	{
		id: 7,
		type: 'phone',
		name: 'Motorola Edge 20 Lite 5G 8/128GB Electric Graphite 90Hz',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 1699.0,
		sale: false,
		image: './images/phone7.png',
	},
	{
		id: 8,
		type: 'phone',
		name: 'realme 9 Pro+ 6+128GB Aurora Green OIS 60W',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 1649.0,
		sale: true,
		saleAmount: 50.0,
		image: './images/phone8.png',
	},
	{
		id: 9,
		type: 'phone',
		name: 'Samsung Galaxy S22 Ultra 12/512GB Green',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 6499.0,
		sale: false,
		image: './images/phone9.png',
	},
	{
		id: 10,
		type: 'phone',
		name: 'Apple iPhone 14 Pro Max 1TB Deep Purple',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 10499.0,
		sale: false,
		image: './images/phone10.png',
	},
	{
		id: 11,
		type: 'laptop',
		name: 'Acer Nitro 5 i5-11400H/16GB/512 RTX3050Ti 144Hz',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 4199.0,
		sale: false,
		image: './images/laptop1.png',
	},
	{
		id: 12,
		type: 'laptop',
		name: 'Apple MacBook Air M1/16GB/256/Mac OS Space Gray US',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 6499.0,
		sale: false,
		image: './images/laptop2.png',
	},
	{
		id: 13,
		type: 'laptop',
		name: 'Dell Inspiron G15 5511 i5-11260H/16GB/512/Win11 RTX3050',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 4199.0,
		sale: true,
		saleAmount: 200.0,
		image: './images/laptop3.png',
	},
	{
		id: 14,
		type: 'laptop',
		name: 'Gigabyte G5 GD i5-11400H/16GB/512 RTX3050 144Hz',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 4349.0,
		sale: true,
		saleAmount: 550.0,
		image: './images/laptop4.png',
	},
	{
		id: 15,
		type: 'laptop',
		name: 'Gigabyte G5 GD i5-11400H/16GB/512 RTX3050 144Hz',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 5999.0,
		sale: false,
		image: './images/laptop5.png',
	},
	{
		id: 16,
		type: 'laptop',
		name: 'Apple MacBook Air M1/8GB/256/Mac OS Space Gray',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 5399.0,
		sale: false,
		image: './images/laptop6.png',
	},
	{
		id: 17,
		type: 'laptop',
		name: 'Razer Blade 15 i7/32GB/1TB/Win11 RTX3070Ti 360Hz',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 16399.0,
		sale: false,
		image: './images/laptop7.png',
	},
	{
		id: 18,
		type: 'tv',
		name: 'Philips 70PUS7956',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 3299.0,
		sale: true,
		saleAmount: 300.0,
		image: './images/tv1.png',
	},
	{
		id: 19,
		type: 'tv',
		name: 'Philips 70PUS8546',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 4499.0,
		sale: false,
		image: './images/tv2.png',
	},
	{
		id: 20,
		type: 'tv',
		name: 'Xiaomi Mi TV Q1 75"',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 6199.0,
		sale: false,
		image: './images/tv3.png',
	},
	{
		id: 21,
		type: 'tv',
		name: 'Samsung QE75Q67BA',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 6499.0,
		sale: false,
		image: './images/tv4.png',
	},
	{
		id: 22,
		type: 'pc',
		name: 'G4M3R HERO i5-12400F/16GB/1TB/RTX3060/W11x',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 6550.0,
		sale: false,
		image: './images/pc1.png',
	},
	{
		id: 22,
		type: 'pc',
		name: 'Acer Nitro 50 i5-11400F/16GB/512 RTX3060Ti',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 5249.0,
		sale: false,
		image: './images/pc2.png',
	},
	{
		id: 23,
		type: 'pc',
		name: 'ASUS ROG Strix G10CE i5-11400F/16GB/512/Win11 RTX3060',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 5399.0,
		sale: true,
		saleAmount: 100.0,
		image: './images/pc3.png',
	},
]
