const products = [
	{
		id: 1,
		category: 'Telefony',
		name: 'Xiaomi Redmi Note 10S 6/128GB Onyx Gray',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 1099.0,
		sale: true,
		saleAmount: 200.0,
		image: './images/phone1.png',
	},
	{
		id: 2,
		category: 'Telefony',
		name: 'Samsung Galaxy A53 5G 6/128GB 120Hz Black',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 2099.0,
		sale: true,
		saleAmount: 400.0,
		image: './images/phone2.png',
	},
	{
		id: 3,
		category: 'Telefony',
		name: 'Samsung Galaxy A32 SM-A325F 4/128GB Black',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 1299.0,
		sale: true,
		saleAmount: 300.0,
		image: './images/phone3.png',
	},
	{
		id: 4,
		category: 'Telefony',
		name: 'Apple iPhone 13 128GB Starlight',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 4499.0,
		sale: false,
		saleAmount: 0,
		image: './images/phone4.png',
	},
	{
		id: 5,
		category: 'Telefony',
		name: 'ASUS ZenFone 8 8/128GB Black',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 2999.0,
		sale: true,
		saleAmount: 700.0,
		image: './images/phone5.png',
	},
	{
		id: 6,
		category: 'Telefony',
		name: 'Apple iPhone 11 64GB Black',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 2599.0,
		sale: false,
		saleAmount: 0,
		image: './images/phone6.png',
	},
	{
		id: 7,
		category: 'Telefony',
		name: 'Motorola Edge 20 Lite 5G 8/128GB Electric Graphite 90Hz',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 1699.0,
		sale: false,
		saleAmount: 0,
		image: './images/phone7.png',
	},
	{
		id: 8,
		category: 'Telefony',
		name: 'realme 9 Pro+ 6+128GB Aurora Green OIS 60W',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 1649.0,
		sale: true,
		saleAmount: 50.0,
		image: './images/phone8.png',
	},
	{
		id: 9,
		category: 'Telefony',
		name: 'Samsung Galaxy S22 Ultra 12/512GB Green',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 6499.0,
		sale: false,
		saleAmount: 0,
		image: './images/phone9.png',
	},
	{
		id: 10,
		category: 'Telefony',
		name: 'Apple iPhone 14 Pro Max 1TB Deep Purple',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 10499.0,
		sale: false,
		saleAmount: 0,
		image: './images/phone10.png',
	},
	{
		id: 11,
		category: 'Laptopy',
		name: 'Acer Nitro 5 i5-11400H/16GB/512 RTX3050Ti 144Hz',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 4199.0,
		sale: false,
		saleAmount: 0,
		image: './images/laptop1.png',
	},
	{
		id: 12,
		category: 'Laptopy',
		name: 'Apple MacBook Air M1/16GB/256/Mac OS Space Gray US',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 6499.0,
		sale: false,
		saleAmount: 0,
		image: './images/laptop2.png',
	},
	{
		id: 13,
		category: 'Laptopy',
		name: 'Dell Inspiron G15 5511 i5-11260H/16GB/512/Win11 RTX3050',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 4199.0,
		sale: true,
		saleAmount: 200.0,
		image: './images/laptop3.png',
	},
	{
		id: 14,
		category: 'Laptopy',
		name: 'Gigabyte G5 GD i5-11400H/16GB/512 RTX3050 144Hz',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 4349.0,
		sale: true,
		saleAmount: 550.0,
		image: './images/laptop4.png',
	},
	{
		id: 15,
		category: 'Laptopy',
		name: 'Gigabyte G5 GD i5-11400H/16GB/512 RTX3050 144Hz',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 5999.0,
		sale: false,
		saleAmount: 0,
		image: './images/laptop5.png',
	},
	{
		id: 16,
		category: 'Laptopy',
		name: 'Apple MacBook Air M1/8GB/256/Mac OS Space Gray',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 5399.0,
		sale: false,
		saleAmount: 0,
		image: './images/laptop6.png',
	},
	{
		id: 17,
		category: 'Laptopy',
		name: 'Razer Blade 15 i7/32GB/1TB/Win11 RTX3070Ti 360Hz',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 16399.0,
		sale: false,
		saleAmount: 0,
		image: './images/laptop7.png',
	},
	{
		id: 18,
		category: 'Telewizory',
		name: 'Philips 70PUS7956',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 3299.0,
		sale: true,
		saleAmount: 300.0,
		image: './images/tv1.png',
	},
	{
		id: 19,
		category: 'Telewizory',
		name: 'Philips 70PUS8546',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 4499.0,
		sale: false,
		saleAmount: 0,
		image: './images/tv2.png',
	},
	{
		id: 20,
		category: 'Telewizory',
		name: 'Xiaomi Mi TV Q1 75"',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 6199.0,
		sale: false,
		saleAmount: 0,
		image: './images/tv3.png',
	},
	{
		id: 21,
		category: 'Telewizory',
		name: 'Samsung QE75Q67BA',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 6499.0,
		sale: false,
		saleAmount: 0,
		image: './images/tv4.png',
	},
	{
		id: 22,
		category: 'Komputery',
		name: 'G4M3R HERO i5-12400F/16GB/1TB/RTX3060/W11x',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 6550.0,
		sale: false,
		saleAmount: 0,
		image: './images/pc1.png',
	},
	{
		id: 22,
		category: 'Komputery',
		name: 'Acer Nitro 50 i5-11400F/16GB/512 RTX3060Ti',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 5249.0,
		sale: false,
		saleAmount: 0,
		image: './images/pc2.png',
	},
	{
		id: 23,
		category: 'Komputery',
		name: 'ASUS ROG Strix G10CE i5-11400F/16GB/512/Win11 RTX3060',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 5399.0,
		sale: true,
		saleAmount: 100.0,
		image: './images/pc3.png',
	},
	{
		id: 24,
		category: 'Klawiatury',
		name: 'Razer Ornata V2',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 349.0,
		sale: true,
		saleAmount: 110.0,
		image: './images/klaw1.png',
	},
	{
		id: 25,
		category: 'Klawiatury',
		name: 'SPC Gear GK630K Tournament Kailh Red RGB',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 215.0,
		sale: false,
		saleAmount: 0,
		image: './images/klaw2.png',
	},
	{
		id: 26,
		category: 'Klawiatury',
		name: 'Logitech G213 PRODIGY',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 249.0,
		sale: false,
		saleAmount: 0,
		image: './images/klaw3.png',
	},
	{
		id: 27,
		category: 'Klawiatury',
		name: 'SPC Gear GK630K Onyx White Tournament Kailh Red RGB',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 279.0,
		sale: false,
		saleAmount: 0,
		image: './images/klaw4.png',
	},
	{
		id: 28,
		category: 'Klawiatury',
		name: 'Redragon Draconic 60% White',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 249.0,
		sale: false,
		saleAmount: 0,
		image: './images/klaw5.png',
	},
	{
		id: 29,
		category: 'Karty Graficzne',
		name: 'Palit GeForce RTX 3050 Dual 8GB GDDR6',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 2149.0,
		sale: true,
		saleAmount: 480.0,
		image: './images/card1.png',
	},
	{
		id: 30,
		category: 'Karty Graficzne',
		name: 'MSI GeForce RTX 3070 Ti GAMING X TRIO LHR 8GB GDDR6X',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 4699.0,
		sale: true,
		saleAmount: 100.0,
		image: './images/card2.png',
	},
	{
		id: 31,
		category: 'Karty Graficzne',
		name: 'Inno3D GeForce RTX 3050 Twin X2 8GB GDDR6',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 1499.0,
		sale: false,
		saleAmount: 0,
		image: './images/card3.png',
	},
	{
		id: 32,
		category: 'Karty Graficzne',
		name: 'Gigabyte GeForce GTX 1660 Ti OC 6GB GDDR6',
		description: `Lorem, ipsum dolor sit amet consectetur adipisicing elit.Expedita quisquam repellendus cumque voluptates!`,
		price: 2099.0,
		sale: true,
		saleAmount: 570.0,
		image: './images/card4.png',
	},
]
